name: FactionsAlly
main: com.roofer.FactionsAlly
version: 1.0
author: roofer
description: Custom spy punishment plugin

commands:
  f spy a:
    description: Spy on your allies faction chat
  f spy t:
    description: Spy on your allies faction chat
  f spy a-t:
    description: Spy on your allies faction chat
